export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_TOPICS_SUCCESS = 'LOAD_TOPICS_SUCCESS';
export const LOAD_CVS_SUCCESS = 'LOAD_CVS_SUCCESS';
export const LOAD_GROUPS_SUCCESS = 'LOAD_GROUPS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
